version: '3.7'

services:
  web:
    build:
      context: ./services/web
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    expose:
      - 5432
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - ./.env.db
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    depends_on:
      - db
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@fedor-solovyev.ru
      - PGADMIN_DEFAULT_PASSWORD=123
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin:/root/.pgadmin
      - pgadmin_app:/home/app/.pgadmin
  nginx:
    build: ./services/nginx
    volumes:
      - static_volume:/home/app/web/project/static
      - media_volume:/home/app/web/project/media
      - /etc/ssl/fedor-solovyev.ru.crt:/etc/ssl/fedor-solovyev.ru.crt
      - /etc/ssl/fedor-solovyev.ru.key:/etc/ssl/fedor-solovyev.ru.key
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
      - pgadmin
volumes:
  static_volume:
  media_volume:
  pgadmin:
  pgadmin_app:
